version: '3.8'

services:
  postgres_node1:
    image: postgres:16.1-alpine
    container_name: postgres_node1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgresnode1user
      - POSTGRES_PASSWORD=postgresnode1pass
      - POSTGRES_DB=sharding
    volumes:
      - ./postgres_node1/data:/var/lib/postgresql/data
    restart: always    

  postgres_node2:
    image: postgres:16.1-alpine
    container_name: postgres_node2
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgresnode2user
      - POSTGRES_PASSWORD=postgresnode2pass
      - POSTGRES_DB=sharding
    volumes:
      - ./postgres_node2/data:/var/lib/postgresql/data
    restart: always

  postgres_node3:
    image: postgres:16.1-alpine
    container_name: postgres_node3
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgresnode3user
      - POSTGRES_PASSWORD=postgresnode3pass
      - POSTGRES_DB=sharding
    volumes:
      - ./postgres_node3/data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: elestio/pgadmin:REL-8_2
    container_name: pgadmin
    ports:
      - "5051:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    restart: always

volumes:
  healthcheck-volume: